src/main/java/org/openrewrite/java/testing/junitassertj/AssertEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/junitassertj/AssertFalseToAssertThat.java
src/test/kotlin/org/openrewrite/java/testing/junitassertj/AssertEqualsToAssertThatTest.kt
src/test/kotlin/org/openrewrite/java/testing/junitassertj/AssertFalseToAssertThatTest.kt

This PR is part of the ongoing work on adding refactoring support to migrate Junit 5 assertions to assertJ.
See https://github.com/openrewrite/rewrite-testing-frameworks/issues/8
This PR adds: 
- A visitor to convert Junit 5's `assertFalse()` to assertJ's `assertThat().isFalse()`
- A visitor to convert Junit 5's `assertEquals()` to assertJ's `assertThat().isEquals()`

Adding assertFalse and assertEquals refactoring visitors

---

src/main/java/org/openrewrite/java/testing/junitassertj/AssertNotNullToAssertThat.java
src/main/java/org/openrewrite/java/testing/junitassertj/AssertNullToAssertThat.java
src/test/kotlin/org/openrewrite/java/testing/junitassertj/AssertNotNullToAssertThatTest.kt
src/test/kotlin/org/openrewrite/java/testing/junitassertj/AssertNullToAssertThatTest.kt

Implemented visitors to convert the following null assertions from JUnit 5 to assertJ.
`assertNull()` => `assertThat().isNull()`
`assertNotNull()` => `assertThat().isNotNull()`

JUnit 5 assertNull / assertNotNull conversions to assertJ

---

src/main/java/org/openrewrite/java/testing/junitassertj/AssertSameToAssertThat.java
src/test/kotlin/org/openrewrite/java/testing/junitassertj/AssertSameToAssertThatTest.kt

Implemented visitor to convert JUnit's `assertSame()` to assertJ's `assertThat().isSameAs()`.
Refrained from creating a generic `ToAssertThat` utility class considering that it would likely get deprecated in a few weeks with the projected changes to TreeBuilder.

Implemented AssertSameToAssertThat visitor

---

src/main/java/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotations.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/kotlin/org/openrewrite/java/testing/junit5/CleanupJUnitImportsTest.kt
src/test/kotlin/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.kt
src/test/kotlin/org/openrewrite/java/testing/junit5/SpringRunnerToSpringExtensionTest.kt
src/test/kotlin/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.kt

This PR introduces logic to reduce the visibility of methods marked with JUnit annotations to "package" to comply with JUnit 5 best practices. Fixes #23

Reduce visibility of JUnit5 methods

---

src/main/java/org/openrewrite/java/testing/junitassertj/JUnitFailToAssertJFail.java
src/test/kotlin/org/openrewrite/java/testing/junitassertj/JUnitFailToAssertJFailTest.kt

Created visitor to migrate from JUnit's `fail(..)` to AssertJ's `fail(..)`.

Created JUnitFailToAssertJFail visitor and tests

---

src/main/resources/META-INF/rewrite/junit5-assertions-to-assertj.yml

In order to enable direct, easy consumption of the JUnit Assertions to AssertJ recipes from the `junitassertj` package, pre-package the recipes in a declarative yaml.
The recipe is titled `JUnit5AssertionsToAssertJMigration` (fully qualified, `org.openrewrite.java.testing.JUnit5AssertionsToAssertJMigration`)

JUnit5 Assertions to Assert J assertions pre-packaged declarative recipes

---

build.gradle.kts

as pr for tracing, will merge after check

move kotlin jvm plugin before nebula-release [openrewrite/rewrite#324] and [openrewrite/rewrite-spring#47]

---

src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
src/test/kotlin/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterizedTest.kt

Add Recipe for migrating JUnit4 `@RunWith(Parameterized.class)` to the Junit 5 Jupiter `ParameterizedTest` equivalent. Fixes #81

Add Recipe for migrating JUnit4 @RunWith(Parameterized.class) to JUnit5 ParameterizedTest

---

src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java

I won't write issues this verbose for other enhancements, but considering the impact this has, I've included additional commentary.
Leaving this PR small as it's impact is significant on it's own (as in, there's room for other enhancements elsewhere). This appears to improve performance  ~300%+ (which isn't scientific, but, hey, it's buzzwordy)
---
I believe this is still semantically correct, and if it's 100% correct I question whether there's value in moving this logic into ChangeType itself as a check since it appears to be quite quick by comparison. But--
Having `FindTypes.find(cu, "org.junit.Test")` check for any types improves execution performance, specifically when tested in against codesets which don't have `org.junit.Test` in it, meaning it's adding drag in situations where the …

Use FindTypes to check for junit4 Test for UpdateTestAnnotation performance [#392]

---

src/jmh/java/org/openrewrite/benchmarks/java/JavaCompilationUnitState.java
src/jmh/java/org/openrewrite/benchmarks/java/assertj/JUnitAssertArrayEqualsToAssertThatBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/assertj/JUnitAssertNotNullToAssertThatBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/assertj/JUnitAssertTrueToAssertThatBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/junit5/AssertToAssertionsBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/junit5/ExpectedExceptionToAssertThrowsBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/junit5/TemporaryFolderToTempDirBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/junit5/UpdateBeforeAfterAnnotationsBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/junit5/UpdateTestAnnotationBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/junit5/UseTestMethodOrderBenchmark.java
src/jmh/java/org/openrewrite/benchmarks/java/mockito/CleanupMockitoImportsBenchmark.java

Includes more benchmarking baselines for relative comparison. Pulled recipes based on grafana. Change however seen fit..
---
scratchpad notes for jmh parameter configuration in build.gradle.kts as per https://github.com/melix/jmh-gradle-plugin/blob/master/samples/simple-java/kotlin-dsl/build.gradle.kts just storing off notes
```
import me.champeau.jmh.JmhParameters
id("me.champeau.jmh") version "0.6.3"
configure<JmhParameters> {
fork.set(1) // @Fork(1)
iterations.set(2) // @Measurement(iterations = 2)
warmupIterations.set(2) // @Warmup(iterations = 2)
//    benchmarkMode = listOf("SampleTime") // @BenchmarkMode(Mode.SampleTime)
//    timeUnit = "s" // @OutputTimeUnit(TimeUnit.SECONDS)
//    threads = 4 // @Threads(4)
//    duplicateClassesStrategy = DuplicatesStrategy.EXCLUDE
}
```

additional benchmarking on recipes for direct comparison

---

src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
src/test/kotlin/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterizedTest.kt

update the ParameterizedRunnerToParameterized recipe to convert ParameterizedRunner tests using Field Injection to the JUnit5 Jupiter ParameterizedTest equivalent. Fixes #102

update the ParameterizedRunnerToParameterized recipe to support field injected parameters

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/kotlin/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterizedTest.kt

Converts the following JUnitParamsRunner `Parameterized` tests to their JUnit5 Jupiter equivalent - fixes #67
- `@Parameters` annotation with out arguments having default `parametersFor...` init-method
- `@Parameters(method = "...")` annotation with method references
- `@Parameters(named = "...")` and associated `@NamedParameter` init-method
Unsupported conversions are identified with a comment on the associated `@Parameters(...)` annotation.

Pragmatists JUnitParamsRunnerToParameterized JUnit Jupiter recipe

---

src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
src/main/java/org/openrewrite/java/testing/junit5/CategoryToTag.java
src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateMockWebServer.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/kotlin/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.kt

adding `getApplicableTest` implementation with HasTypes check to JUnit Migration recipes and fixing the JunitMockitoUpgradeIntegrationTest.theBigOne test

fix JunitMockitoUpgradeIntegrationTest.theBigOne and add getApplicableTest implementations

---

src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/kotlin/org/openrewrite/java/testing/junit5/MigrateJunitTestCaseTest.kt
src/test/kotlin/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.kt

JUnit 4 to 5 migration recipe for junit.framework.TestCase.  Fixes #78

JUnit 4 to 5 TestCase migration recipe.

---

.github/workflows/publish.yml
build.gradle.kts

This removes the "-x test" from the release builds, so they will now run tests. That takes a bit longer, but the previous CI runs will have been built against snapshots so they wont necessarily be valid results for releasing.

Use latest.integration when building normally, latest.release when releasing

---

src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
src/test/kotlin/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.kt

TemporaryFolderToTempDir generates a method declaration for creating new folders and then generates method invocations for the new method declaration.  This fixes a bug where the newly generated method invocations were not fully type attributed.

TemporaryFolderToTempDir bug fix where the newly generated method invocations were not fully type attributed.

---

src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
src/test/kotlin/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.kt

ExpectedExceptionToAssertThrows asserts the expected message string. Fixes #153
@skingsland, thanks again for identifying this issue.  The solution is slightly different from your suggestion because the `AssertToAssertions` does not assume AssertJ is on the classpath.
```java
public void statementsBeforeExpected() {
Throwable exception = assertThrows(IndexOutOfBoundsException.class, () -> {
int[] a = new int[]{1};
int b = a[1];
});
assertTrue(exception.getMessage().contains("Index 1 out of bounds for length 1"));
}
```

Fix expected exception expect exception message string

---

src/main/resources/META-INF/rewrite/junit5.yml

Move the vertx runner to extension recipe into its own declarative recipe which also adds the Vertx Junit5 dependency.

Move the vertx runner to extension recipe into its own declarative recipe

---

src/main/java/org/openrewrite/java/testing/junit5/EnclosedToNested.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/kotlin/org/openrewrite/java/testing/junit5/EnclosedToNestedTest.kt

Couple caveats:
* The test case expectations have some extraneous whitespace, tied to this issue here: https://github.com/openrewrite/rewrite/issues/1912
* I expect the full test suite will throw some "Unable to construct Java11Parser" exceptions, same as #232, but on my local those are the *only* test failures

Added EnclosedToNested recipe for JUnit4 to JUnit5 migration

---

.gitignore
src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueEqualsToAssertEquals.java
src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertTrueEqualsToAssertEqualsTest.kt

Only replace assertTrue(x.equals(...)) if equals has a single argument

---

src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java
src/test/kotlin/org/openrewrite/java/testing/cleanup/RemoveTestPrefixTest.kt

Came across this when migrating a large repository; potential source of errors to avoid.

Do not strip prefix when remainder results in methods such as toString()

---

src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java
src/test/kotlin/org/openrewrite/java/testing/cleanup/RemoveTestPrefixTest.kt

Small addition after exposure to new code base.

Strip test_ prefix from snake cased methods

---

src/main/java/org/openrewrite/java/testing/junit5/LifecycleNonPrivate.java
src/main/java/org/openrewrite/java/testing/junit5/TempDirNonFinal.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/kotlin/org/openrewrite/java/testing/junit5/LifecycleNonPrivateTest.kt
src/test/kotlin/org/openrewrite/java/testing/junit5/TempDirNonFinalTest.kt

Could I get some guidance on how to get the desired whitespace to work?
All attempts I did with Space so far made things worse. :)
```java
org.opentest4j.AssertionFailedError: 
expected: 
"import org.junit.jupiter.api.BeforeEach;
class A {
@BeforeEach
void beforeEach() {
}
}"
but was: 
"import org.junit.jupiter.api.BeforeEach;
class A {
@BeforeEach void beforeEach() {
}
}"
```

Add LifecycleNonPrivate for JUnit 5.9.0 (#241)

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueComparisonToAssertEquals.java
src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNegationToAssertFalse.java
src/main/java/org/openrewrite/java/testing/junit5/CategoryToTag.java
src/main/java/org/openrewrite/java/testing/junit5/EnclosedToNested.java
src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java
src/main/java/org/openrewrite/java/testing/junit5/TempDirNonFinal.java
src/test/kotlin/org/openrewrite/java/testing/junit5/TempDirNonFinalTest.kt

Based on feedback received in https://github.com/openrewrite/rewrite-testing-frameworks/pull/252#issuecomment-1221326960
> JavaRecipeTest is being replaced with [RewriteTest](https://docs.openrewrite.org/tutorials/recipe-testing#rewritetest-interface)

RewriteTest for TempDir and cleanup unused imports & deprecations

---

src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
src/test/kotlin/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.kt

Depends on https://github.com/openrewrite/rewrite/pull/2160
Apps which use Lombok are especially vulnerable to issues with the JUnit4 to 5 Migration recipe, as they commonly use Lombok-generated getters within `assert` statements, which breaks type information for the whole line and causes those `assert` invocations to "hide" from the recipe.
This PR improves the migration's resiliency in those cases by allowing matching on unknown types.

Improved JUnit AssertToAssertions behavior with missing type info

---

src/main/java/org/openrewrite/java/testing/junit5/AddMissingNested.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/kotlin/org/openrewrite/java/testing/junit5/AddMissingNestedTest.kt

Add missing @Nested annotation

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/cucumber/DropSummaryPrinter.java
src/test/java/org/openrewrite/java/testing/cucumber/DropSummaryPrinterTest.java

@mpkorstanje do you agree with the samples & replacements here? Should we cover any other cases?
The deprecation notes mentioned EventListeners, but might require further changes.

Drop SummaryPrinter #264

---

src/main/resources/META-INF/rewrite/cucumber.yml

This was missing in the 7.x upgrade; didn't think it necessary to add this into older versions.

UpgradeDependencyVersion for io.cucumber:* to 7.x

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationJavaTest.java

To work correctly, we need to fix a bug in `JavaTemplate` for using the replace coordinate on a `J.Annotation`. Currently creates an uncompilable template:

Replace JUnit @Test when it is fully qualified

---

src/main/resources/META-INF/rewrite/junit5.yml

depends on just-pushed new recipe in rewrite; snapshot builds might not be caught up yet

JUnit 5 migration now removes surefire-junit plugins

---

src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublic.java
src/test/java/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublicTest.java

TestsShouldNotBePublic recipe:  if the JUnit class is public and abstract, it should be ignored.

fix abstract class logic in TestsShouldNotBePublic

---

src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java

When i tried this recipe on my project there where soms imports that where removed while stil in use. That is because i used given() and this is in mockito core (BDDMockito) and those where not in this recipe that is why i made this pr
See here for the BDDMockito java doc
https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/BDDMockito.html
I appriciate the feedback, thanks for this project

Add BDDMockito methods to the MOCKITO_METHOD_NAMES

---

src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java

By running the recipe, statements importing this method are removed.
This method still is in [Mockito](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#verifyNoInteractions(java.lang.Object...)) and is not deprecated.

verifyNoInteractions should not be removed

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java

This PR adds support for rewriting JUnit assertions to AssertJ assertions for throwing member references.
Lambdas in the form of `() -> { throw new Exception(); }` were already supported. Now `var::throwingMemberReference` is  also supported.
I'm not really sure what rewrite's default behavior is for unsupported semantics; the added code simply does not rewrite unsupported semantics. Alternatively, the PR can be adjusted to throw an `IllegalArgumentException` in the last if-else branch.

Support member references in AssertJ assertThrows

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java

This PR adds a unit test `assertThrowsAssignment` that generates invalid code. In JUnit `assertThrows` returns the exception that is thrown, while in AssertJ there is no way (currently) to obtain the exception that is thrown.
The purpose of this PR is check whether it is desired behavior open rewrite generates invalid Java code. A solution would be to skip rewriting cases where `assertThrows` is used as RHS in an assignment, but that would leave JUnit assertions in code bases.

Add test that generated invalid code

---

src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5BestPracticesTest.java

Recently migrated using openrewrite and was missing this recipe. Possibly not as simple as a ChangeType recipe.

Add JUnit ThrowingRunnableToExecutable recipe

---

src/main/java/org/openrewrite/java/testing/assertj/UseExplicitContains.java
src/main/java/org/openrewrite/java/testing/assertj/UseExplicitIsEmpty.java
src/main/java/org/openrewrite/java/testing/assertj/UseExplicitSize.java
src/test/java/org/openrewrite/java/testing/assertj/UseExplicitisEmptyTest.java

I have added a new recipe to simplify assertions in tests that use AssertJ isEmpty().
Specifically, this recipe simplifies assertThat(collection.isEmpty()).isTrue() into assertThat(collection).isEmpty() and assertThat(collection.isEmpty()).isFalse() into assertThat(collection).isNotEmpty()
I work a lot with AssertJ and I have lots of legacy code to cleanup assertions.
This is similar to other recipes I have contributed, so there should be no big issue.

Added recipe to use explicit isEmpty in AssertJ assertions

---

src/main/resources/META-INF/rewrite/mockito.yml

Disabled ReplacePowerMockito
https://github.com/openrewrite/rewrite-testing-frameworks/issues/358

Remove ReplacePowerMockito from inclusion in Mockito1to3

---

src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJTest.java

Fix `HamcrestMatcherToAssertJ` when applied to arrays

---

src/main/resources/META-INF/rewrite/hamcrest.yml
src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java

Hamcrest's `contains` matches AssertJ's `containsExactly`. AssertJs `contains` does not care about order and completeness. Hamcrests `contains` does, see the [docs](https://hamcrest.org/JavaHamcrest/javadoc/2.1/org/hamcrest/Matchers.html#contains-E...-)!
Fix this bug.
Should I create an issue or is just the pr fine?
Another topic: I am not so sure about the mapping of [containsInRelativeOrder to containsExactly](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/hamcrest.yml#L148C30-L148C30) as I don't know how `containsInRelativeOrder` works. From the docs I don't understand if it matches for completeness in both directions. Kind of related to this pr, but also a different topic.
no
It is a bug to me.

fix: assertj contains is weaker than hamcrests contains

---

src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
src/test/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcherTest.java

This PR fixes an issue where the recipe that removed `is()` invocations would remove them even when they were not found directly inside of an `assertThat` invocation.
[#365](https://github.com/openrewrite/rewrite-testing-frameworks/issues/365)
I added two tests based off of the last comment on the ticket. Both tests now pass in this PR, so I think the bug should be fixed. I think how I implemented the fix shouldn't interfere with any other parts of the recipe.
@timtebeek

Limit `RemoveIsMatcher` to invocations within `assertThat`

---

src/main/resources/META-INF/rewrite/hamcrest.yml
src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java

The containsInRelativeOrder matcher recipe has been removed from the `hamcrest.yml` list. 
[this issue](https://github.com/openrewrite/rewrite-testing-frameworks/pull/371#issuecomment-1622442507)
@timtebeek 
It seems that there is currently no direct replacement for the hamcrest matcher `containsInRelativeOrder`in AssertJ. The closest method in AssetJ would be `containsExactlyInOrder` but these two methods are not *quite* the same.

removed containsInRelativeOrder from yaml list

---

src/main/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOf.java
src/test/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOfTest.java

Added recipe which migrates JUnit4 (or JUnit5) assertTrue(x instanceof y) into JUnit5 assertInstanceOf(y.class, x)
Added recipe which migrates JUnit4 (or JUnit5) assertTrue(x instanceof y) into JUnit5 assertInstanceOf(y.class, x)

Assert instance of migration

---

src/main/resources/META-INF/rewrite/mockito.yml

Restore AnyToNullable after 7b2c98bf2792ce59afc31ab649ea3c4c1b9db126 and reimplementation in #378 by @nmck257
Recipe should no longer make excessive changes; meaning it can be restored to migrate from Mockito v1 to v2 without semantic changes and potential breaking tests.

Restore now Scanning AnyToNullable, as it does not affect Mockito 2+

---

src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.java
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java

Added a test case to cover the mentioned use case.
- assertEquals in JUnit4 accepts Object[], to preserve the behaviour we need to rewrite it into assertArrayEquals
https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html#assertEquals(java.lang.Object%5B%5D,%20java.lang.Object%5B%5D)

Migrate assertEquals with array parameter to assertArrayEquals

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/hamcrest/FlattenAllOf.java
src/main/resources/META-INF/rewrite/hamcrest.yml
src/test/java/org/openrewrite/java/testing/hamcrest/FlattenAllOfTest.java
src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java

Convert Hamcrest `allOf(Matcher...)` to individual `assertThat` statements for easier migration.
For #357
Correct use of cursor & coordinates.
Initially tried with `visitMethodInvocation`, but that also complained when inserting more than one statement, even when part of the same JavaTemplate string.

Flatten Hamcrest assertThat allOf

---

src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestNotMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
src/main/resources/META-INF/rewrite/hamcrest.yml
src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJTest.java

Replace Hamcrest `is` with AssertJ where the argument is not a matcher.
https://github.com/openrewrite/rewrite-testing-frameworks/issues/357#issuecomment-1644743209

Replace Hamcrest `is` with AssertJ

---

src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java

Remove separate handling of two vs three arguments cases; remove `applySpecialCases`.
`closeTo` was now only supported for two arguments; duplication made that hard to spot & maintain.

Reduce duplication and migrate closeTo with three arguments

---

src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestAnyOfToAssertJ.java
src/main/resources/META-INF/rewrite/hamcrest.yml
src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestAnyOfToAssertJTest.java

This PR adds a recipe that migrates Hamcrest `anyOf` matchers to AssertJ `satisfiesAnyOf` assertions.
[#357](https://github.com/openrewrite/rewrite-testing-frameworks/issues/357)
This first test almost passes, however it does not add the needed import for AssertJ's `AbstractAssert`. I've added the classpath resources in the `JavaTemplate`, and used both `.imports()` and `maybeAddImport()`.
@timtebeek

Migrate Hamcrest `anyOf` matchers to AssertJ `satisfiesAnyOf` assertions

---

src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java

Don't attempt to remove Mockito class import when we know method calls use it
Without this change, in classes that use both Class-qualified method calls and static method calls, 
the recipe will attempt to remove the Mockito class import.
RemoveImports is smart enough to not do this, but it does remove the static method import instead,
even if it is used. I do not fully understand why, so I don't feel comfortable proposing a fix to RemoveImports.
Instead, I accept it as a limitation of RemoveImports and have added logic to the recipe to not attempt to remove the class import if we know it is directly referenced.
This might not be the most elegant solution, so please let me know if there is a better way to handle this.
Also, let me know if there are any other test cases that should be …

Fix problem with incorrectly removed Mockito imports

---

src/main/java/org/openrewrite/java/testing/assertj/AdoptAssertJDurationAssertions.java
src/test/java/org/openrewrite/java/testing/assertj/AdoptAssertJDuractionAssertionsTest.java
src/test/java/org/openrewrite/java/testing/assertj/AdoptAssertJDurationAssertionsTest.java

This PR introduces a recipe that simplifies some AssertJ duration assertions with dedicated asserts and also simplifies some `Duration`s to easier to read forms.
Ex:
```
- .hasHours(48)
+ .hasDays(2)
```
[#400](https://github.com/openrewrite/rewrite-testing-frameworks/issues/400)
@timtebeek

Adopt AssertJ duration assertions

---

src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java

updated the used constructor
To help fix the build
n/a

fix: update used FindImports constructor to not match inherited

---

src/main/resources/META-INF/rewrite/jmockit.yml

Added addDependency for Mockito
In case a rewrite from JMockito to Mockito happens, the build does not break.

feat: add mockito dependency if needed

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertEqualsBooleanToAssertBoolean.java
src/main/java/org/openrewrite/java/testing/cleanup/AssertNotEqualsBooleanToAssertBoolean.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/cleanup/AssertEqualsBooleanToAssertBooleanTest.java
src/test/java/org/openrewrite/java/testing/cleanup/AssertNotEqualsBooleanToAssertBooleanTest.java

Improves the current cleanup rules by refactoring `assertEquals(false, a.methodCall(...))` to `assertFalse(a.methodCall(...))`

Refactor `assertEquals(<boolean-literal>, …)` and `assertNotEquals(<boolean-literal>, …)` to `assertTrue` or `assertFalse`

---

src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoWhen.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitToMockitoTest.java

- Refactored the recipe to visit `J.MethodDeclaration` instead of `J.NewClass`. When attempting to substitute the `J.NewClass` with multiple `J.MethodDeclaration` LSTs, the old recipe would fail.
- Added support for multiple expectations statements.
Continuation of #415. 
This is still an incomplete implementation, but now handles multiple expectations defined within a JMockit `Expectations` block.

Jmockit Expectations - Handle Additional Cases

---

src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockito.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoWhen.java
src/main/resources/META-INF/rewrite/jmockit.yml
src/test/java/org/openrewrite/java/testing/jmockit/JMockitToMockitoTest.java

- Added handling for [Argument Matchers](https://jmockit.github.io/tutorial/Mocking.html#argumentMatching).
- Added handling for Void methods in Expectations blocks.
Continuation of #418.
This recipe is still incomplete, pending handling of `times`, `minTimes`, and `maxTimes` fields of `Expectations` blocks in a subsequent PR.

JMockit to Mockito Recipe - Handle Argument Matchers and Void Methods

---

src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockito.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitToMockitoTest.java

Continuation of #419.
Handle JMockit typed argument matchers like `mockInstance.anyMethod((List<String>) any)`.

JMockit to Mockito Recipe - Handle Typed Class Argument Matching and Collections

---

src/main/resources/META-INF/rewrite/junit5.yml

This was required in JUnit 3, yet persists through to today; let's get rid of that now.

Remove test prefix with JUnit best practices

---

src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
src/main/resources/META-INF/rewrite/mockito.yml
src/test/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockitoTest.java

This commit does not yet close the issue, as there are other cases, where this can potentially go wrong.
It also appears strange that the recipe matches on Mockito's `mockStatic()` rather than on PowerMock's `mockStatic()`. Therefore, the recipe is for now excluded from `Mockito1to3Migration`, as this is part of `JUnit4to5Migration` which is widely used.
Issue: #360

Don't remove `mockStatic()` calls in resources of try-with-resources

---

src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestNotMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestOfMatchersToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJTest.java

https://github.com/openrewrite/rewrite-testing-frameworks/issues/357#issuecomment-1809958904
We could also first change the imports from CoreMatchers to Matchers, but that might have side effects not overseen here.

Replace Hamcrest CoreMatchers as well using wildcards

---

src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java

- Added a testcase for build errors due to missing Junit4 dependencies
- Added workaround to JUnit4to5Migration: Undo the exclusion
Fixes #429

Fixes broken testcontainer dependencies after JUnit4to5Migration

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/testcontainers/ExplicitContainerImage.java
src/main/java/org/openrewrite/java/testing/testcontainers/package-info.java
src/main/resources/META-INF/rewrite/testcontainers.yml
src/test/java/org/openrewrite/java/testing/testcontainers/ExplicitContainerImageTest.java
src/test/java/org/openrewrite/java/testing/testcontainers/TestcontainersBestPracticesTest.java

Add recipes to rewrite testcontainers, as rewritten for Rewrite 8 from https://github.com/openrewrite/rewrite-testcontainers
Fixes https://github.com/openrewrite/rewrite-testcontainers/issues/1
I've crudely stripped out individual recipes and tests where I saw duplication; rather we can just run an aggregate `ExplicitContainerImages` that will match whatever is present. I'll add the other recipes that were present still.
@eddumelendez @kiview
Integrated here such that these recipes can be used from a JUnit Jupiter migration, and themselves reuse other recipes from there.
- https://github.com/openrewrite/rewrite-testcontainers/issues/1

Rewrite testcontainers to use explicit image and version

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrder.java
src/test/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrderTest.java

Also swap the order of arguments to `assertNull` and `assertNotNull`.
Mistake easily made if migrating manually, especially at scale.

Also swap assertNull and assertNotNull argument order

---

src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java
src/test/java/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.java

Fixes #441
UpdateTestAnnotation does not change the visibility modifier anymore.
I updated the test as needed.
I removed the following 2 tests in UpdateTestAnnotationTest as they make no sense after the change:
privateToPackageVisibility()
protectedToPackageVisibility()

Do not change visibility in `UpdateTestAnnotation`; use `TestsShouldNotBePublic` instead

---

src/main/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotations.java
src/test/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotationsTest.java

This PR contains another enhancement to the AddMissingTestBeforeAfterAnnotations recipe.
see #443, #444, #445
The current implementation did not handle the case correctly where the test annotations where not on the superclass itself,
but on an ancestor class up in the hierarchy. With this fix, not only the superclass but all classes up in the hierarchy are checked.
See new test addMissingTestBeforeAfterAnnotationsIfExtended

AddMissingTestBeforeAfterAnnotations is looking for annotations in all ancestor classes

---

src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java

Fixes #450
- #450
Quickest way to fix this is to add an explicit unit, since any division might lead to rounding errors.
We could also explore simplifying the durations as we do for AssertJ
https://github.com/openrewrite/rewrite-testing-frameworks/blob/24742fb4458d71f11103116090a3337612ca8187/src/main/java/org/openrewrite/java/testing/assertj/AdoptAssertJDurationAssertions.java#L165-L203
But that's probably best done as a separate followup recipe such that we also pick up any existing tests.

Add unit to `@Timeout`

---

src/main/resources/META-INF/rewrite/junit5.yml

`mockwebserver3-junit5` is not necessary for JUnit5 compatibility; only to provide the relevant `Extension`. And given that the corresponding JUnit4 Rule seems to have been introduced in the same okhttp version (5.x), it is unlikely for existing apps on JUnit4 to have usages non-JUnit-5-compatible code (and even if they do use the MockWebServerRule, this recipe does not yet convert that to MockWebServerExtension anyway). there's also a version management concern here; moving to an "alpha" version of a dep may surprise/confuse users, and, moving *only* mockwebserver to that version (without touching other okhttp deps) may risk compatibility issues
cc @knutwannheden since this came from your commit (a while ago) https://github.com/openrewrite/rewrite-testing-frameworks/commit/1bf96d3982571b2 …

removing UpgradeOkHttpMockWebServer from JUnit5 upgrade

---

src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/ExpectationsBlockRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockito.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitUtils.java
src/main/java/org/openrewrite/java/testing/jmockit/SetupStatementsRewriter.java
src/main/resources/META-INF/rewrite/jmockit.yml
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java

**Improvements:**
- Added support for `minTimes` and `maxTimes` JMockit features.
- Several pieces of logic depended on the instance of the LST element (e.g. `J.Literal` or `J.Identifier`) rather than the `JavaType` itself. Refactored to use the more appropriate type matching.
- Argument matcher convenience methods like `anyString` or `anyLong` were not uniformly applied and in some cases `any(java.lang.String)` would be used instead. Use the convenience APIs consistently.
- The recipe had several scenarios where an exception is intentionally thrown in order to prevent processing LSTs that contain either invalid or unhandled LST structures. Change this to instead simply return the LST elements unchanged and continue processing rather than short-circuiting the entire recipe.
**Bug Fixes:** …

JMockit to Mockito Recipe - Bug Fixes and Improvements

---

src/main/resources/META-INF/rewrite/assertj.yml
src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionTest.java
src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionWithOptionalTest.java

New AssertJ simplifications: 
|Before|After|
|-|-|
|assertThat(anOptional.isEmpty()).isFalse() |assertThat(anOptional).isNotEmpty()|
|assertThat(anOptional.isEmpty()).isTrue()  |assertThat(anOptional).isEmpty()|
|assertThat(anOptional.isPresent()).isFalse()|assertThat(anOptional).isNotPresent()|
|assertThat(aString.contains("foo")).isFalse()|assertThat(aString).doesNotContain("foo")|
|assertThat(aMap.isEmpty()).isTrue()|assertThat(aMap).isEmpty()|
|assertThat(aMap.isEmpty()).isFalse()|assertThat(aMap).isNotEmpty()|
(`assertThat(anOptional.isPresent()).isTrue()` is already covered)
#
closing https://github.com/openrewrite/rewrite-testing-frameworks/issues/466 + adding additional transformations

Add more simplifications

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNull.java
src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNull.java
src/test/java/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNullTest.java
src/test/java/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNullTest.java

Limit AssertTrueNullToAssertNull and AssertFalseNullToAssertNotNull to binary equals that contain a `null` literal.

Limit AssertTrueNullToAssertNull applicability

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThatTest.java

`JUnitAssertEqualsToAssertThat` skipped adding `assertThat` import for custom classes

---

src/main/java/org/openrewrite/java/testing/jmockit/JMockitMockedVariableToMockito.java
src/main/resources/META-INF/rewrite/jmockit.yml
src/test/java/org/openrewrite/java/testing/jmockit/JMockitMockedVariableToMockitoTest.java

Improvements:
- Added support for JMockit Mocked Variable features(eg. `void someMethod(@Mocked Object o)`)

JMockit to Mockito Recipe - Rewrite JMockit Mocked Variable to Mockito statements

---

src/main/java/org/openrewrite/java/testing/junit5/TempDirNonFinal.java
src/test/java/org/openrewrite/java/testing/junit5/TempDirNonFinalTest.java

Fixes #483.
apply TempDirNonFinal only to fields, not method parameters
Without the main code fix, the modified test fails.
The method for detecting whether the variables are fields or method arguments has been copied from another recipe. There are multiple (different) implementations of this method all over the place, and I have no idea if the other implementations are better or not. Someone from the core team might want to introduce an actual API method for that to avoid these local duplicates.

don't use TempDirNonFinal on method parameters

---

src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/ExpectationsBlockRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockito.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java

This PR includes these major changes:
- Expectations with raw values mixed with argument matchers should use `eq`
- Preserve the type information of Mockito `any(Class)` invocation arguments
- Fix infinite loop when rewriting `Expectations` block fails
- Major refactor of `ArgumentMatchersRewriter` to simplify logic and add clarity 
Continue improving the recipe, make it easier to understand.

JMockit to Mockito Recipe - `eq` Support, Better Type Propagation, and Error Handling

---

src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestOfMatchersToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/RemoveIsMatcher.java
src/main/java/org/openrewrite/java/testing/hamcrest/package-info.java
src/main/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocks.java
src/main/java/org/openrewrite/java/testing/testcontainers/ExplicitContainerImage.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/XkVt46WER?organizationId=T3BlblJld3JpdGU%3D

refactor: Recipe nullability best practices

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrder.java

fixed typo, negation was missing

Update AssertionsArgumentOrder.java: fix typo, missing negation

---

src/main/java/org/openrewrite/java/testing/cleanup/SimplifyTestThrows.java
src/test/java/org/openrewrite/java/testing/cleanup/SimplifyTestThrowsTest.java

New recipe for replacing exception subclasses in test method signatures by java.lang.Exception, to improve readability. I'm not sure if there is any static code analysis guideline demanding this. I _am_ sure that there are different opinions by developers whether to declare `void test throws MyVerySpecialException` or just `...Exception`. Nevertheless I do need this recipe at work, and maybe it's useful for others, too.
You may want to look at the DocumentExample in the test to see the main idea. Feel free to suggest a different name or description.
The "is this a test" detection has been copied from another recipe. I'm not sure if it would be useful to have some helper classes there to unify that.

Recipe to make tests throw at most a single Exception

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertFalseToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotNullToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNullToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertSameToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertTrueToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitFailToAssertJFail.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertNotNullToAssertThatTest.java

Since commit https://github.com/openrewrite/rewrite-testing-frameworks/commit/368384a174bd92d49880c19a879fb9e14afcfa27 , AssertJ recipes are really slower since calling `contextSensitive()` method  disable a cache on JavaTemplate.
Fixes:
- Make sure there is a static import org.assertj.core.api.Assertions.* , even if not referenced (see #491 and #479)
- reintroduced assertionsParser cache in JUnitAssertEqualsToAssertThat

Fix performance regression in AssertJ recipes

---

src/main/resources/META-INF/rewrite/hamcrest.yml

I've added 2 'notMatcher's to HamcrestNotMatcherToAssertJ.
I've added two notMatcher's that were not automatically changed in my project. By adding these two it fixed my problem.
-
-
-
-

Added to notMatchers

---

src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java

Add a precondition to only upgrade maven-surefire-plugin on older versions of Maven.
Prevent adding noise when already using a recent Maven release.
- https://github.com/openrewrite/rewrite/pull/4206

Only upgrade maven-surefire-plugin on older Maven versions

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/junit5/CleanupJUnitImports.java
src/test/java/org/openrewrite/java/testing/junit5/CleanupJUnitImportsTest.java

Some of the recipes were not working with Kotlin code bases, i would like to add this one as a first example and will change the rest of the recipes the same way after the feedback. More MRs to follow. 
The change is around the usage of visitCompilationUnit, this visitor doesn't work with Kotlin codebases , i made the change to use preVisit, and this seems to fix it.
we would like to make the recipes work on Kotlin codebases
Please let me know if this is the correct way, especially to add tests for both Kotlin and Java together like the way I have done.
@timtebeek @knutwannheden 
Nope

Add Kotlin support for Junit 5 recipes 1: CleanupJUnitImports

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyString.java
src/main/resources/META-INF/rewrite/assertj.yml
src/test/java/org/openrewrite/java/testing/assertj/AssertJBestPracticesTest.java

Leverage existing Refaster recipes to apply more small fixes for users of AssertJ
I'd tried to remove `AbstractStringAssertStringIsEmptyRecipe` to replace `IsEqualToEmptyString`, but that's not matching, possibly due to generics. (cc @knutwannheden)
- #513
- #525

Add Picnic AssertJ rules to AssertJ best practices

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyString.java
src/main/resources/META-INF/rewrite/assertj.yml

Drop rewrite-third-party dependency.
Brought in a Java 17 requirement due to classes being compiled with Java 17, whereas we want to continue to support Java 8.
- https://github.com/openrewrite/rewrite-third-party/issues/11

Drop Java 17 requirement through rewrite-third-party

---

src/main/java/org/openrewrite/java/testing/jmockit/ExpectationsBlockRewriter.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java

Currently Jmockit Expectation statements when they do not have a times or result, when migrated to mockito disappear. However, when migrated to mockito, it should have a corresponding verify statement as per following documentation:
1. https://www.baeldung.com/jmockit-expectations section 2.4 "Then we used the default behavior (if no repetition constraint is given minTimes = 1; is used) to define that at least one invocation will be done to methodForTimes2()"
2. https://jmockit.github.io/tutorial/Mocking.html section 6.2
From my experience, when people specify this in the Expectation, it almost always corresponds to a mockito verify with no explicit times, basically saying that this statement occurs exactly once. 
In mockito usually times is used to specify the exact number of invocations …

Jmockit Expectations with no times or result should be transformed to Mockito verify statement

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java

Add a NoMissingTypes Precondition to CleanupMockitoImports, to prevent changes if types are missing
Fix issue where `org.mockito.kotlin` imports were being removed although they were in use.
Following suggestion by @timtebeek in Slack channel.
Possibly the unit test should use a Kotlin code block and not a Java one? not sure about this.
@timtebeek

Add a NoMissingTypes Precondition to CleanupMockitoImports

---

src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockToMockito.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockType.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitUtils.java
src/main/java/org/openrewrite/java/testing/jmockit/SetupStatementsRewriter.java
src/main/resources/META-INF/rewrite/jmockit.yml
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java

Tests are failing, need to fix and also add tests once they pass. The import for verify is not being added. I don't know why this is not working as it is working for the when statements and the same code is being used.
https://jmockit.github.io/tutorial/Mocking.html#verification
https://www.javadoc.io/doc/org.jmockit/jmockit/1.45/mockit/Verifications.html

Migrate JMockit Verifications to Mockito

---

src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java
src/test/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefixTest.java

Partial fix for
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/258
As suggested by @protocol7

Skip RemoveTestPrefix when calling a similarly named method

---

src/main/resources/META-INF/rewrite/junit5.yml

AssertTrueNullToAssertNull is unexpectedly missing from CleanupAssertions.

Add AssertTrueNullToAssertNull to CleanupAssertions

---

src/main/java/org/openrewrite/java/testing/assertj/IsEqualToBoolean.java
src/main/resources/META-INF/rewrite/assertj.yml
src/test/java/org/openrewrite/java/testing/assertj/IsEqualToBooleanTest.java
src/test/java/org/openrewrite/java/testing/assertj/IsEqualToEmptyStringTest.java
src/test/java/org/openrewrite/java/testing/assertj/MigrateChainedAssertToAssertJTest.java

1 - Created a new recipe that converts `assertThat( true ).isEqualTo( true )` to `assertThat( true ).isTrue()`, same for false
2 - added new recipe to best practices on assertJ
3 - Added ChainedAssertions for Iterator hasNext
Noticed a lot of `isEqualTo(true)` on https://github.com/OpenFeign/querydsl/ and want to get it sorted
Hrmm, I'm a little short of intellij, can anyone help me out of formatting this, sorry

More best pratices for AssertJ

---

src/main/resources/META-INF/rewrite/assertj.yml
src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/assertj/MigrateChainedAssertToAssertJTest.java
src/test/java/org/openrewrite/java/testing/junit5/CleanupAssertionsTest.java
src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java

Instead of using:
```
assertThat(cat.toString()).isEqualTo("animal");
```
Could use:
```
assertThat(cat).hasToString("animal");
```

Simplify toString assertion

---

src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java

As [discussed on Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1721792132436429) with @shivanisky .

ExpectedExceptionToAssertThrows should not wrap single statement

---

src/test/java/org/openrewrite/java/testing/jmockit/JMockitDelegateToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java

At the moment, JMockit Delegates are not migrated to mockito as mentioned in issue
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/522. 
What I'm seeing is that they are being trashed with the template being printed out. These tests were written to try to replicate this issue, however I was unable to.
They may help anyone adding the feature for Delegate migration.
https://javadoc.io/doc/org.jmockit/jmockit/latest/mockit/Delegate.html
Also added one test case showing comments are not preserved.
I am wondering if it's better to have the test cases failing with the expected output and to disable them. Please let me know if that's preferred.
@timtebeek @tinder-dthomson

Add unit tests for JMockit Delegate to mockito migration. Also add test case for comments

---

src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java

- Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/563

Remove throws from method that adopts `assertThrows`

---

build.gradle.kts
src/main/resources/META-INF/rewrite/assertj.yml

Restore
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/531
Following
- https://github.com/PicnicSupermarket/error-prone-support/pull/1270
Use existing refaster style recipes maintained at EPS, to avoid duplicate efforts.

Use error-prone-contrib AssertJ recipes

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java
src/test/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java

Test case for inlining valid single line assertthrows
Inline valid single line assert throws test case
This recipe creates intellij suggestion/warning to inline this code and I much prefer it inlined, saves 2 lines of useless code.
@timtebeek 
Yes - maybe a separate recipe which achieves this is better, or maybe both - change this recipe, and have a separate recipe. Can do separate recipe first as it addresses at a global level.

Convert lambda block to expression after adopting `assertThrows`

---

src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
src/test/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockitoTest.java

Add minimalistic testcase to show that when a static nested class is mocked, it tries to add a field declaration but the JavaTemplate breaks duplicating fields and methods.
@timtebeek

`PowerMockitoMockStaticToMockito` duplicates variables and methods when static nested class is involved

---

src/main/resources/META-INF/rewrite/junit5.yml

Precondition added to `JUnit4to5Migration` that checks whether testNG is used
@timtebeek

Do not perform `JUnit4to5Migration` where TestNG is used

---

src/main/java/org/openrewrite/java/testing/junit5/AssertThrowsOnLastStatement.java
src/test/java/org/openrewrite/java/testing/junit5/AssertThrowsOnLastStatementTest.java

In multi line assertThrows move assertThrows to last statement only
Currently the Junit 4 to 5 recipe migrates the @Test junit 4 annotation to wrap the entire method to assertThrows when typically we want it on the last statement.
@timtebeek 
Yes - may be modifying the existing recipe is better? Rather than providing an extra recipe to move existing assertThrows with multi line lamdbas to the last statement only, but we can hook this recipe in optionally, so ... maybe not. Maybe that can be an optional argument in the existing recipe - move applyAssertThrowsToLast and the user can set it to true if they are ok to take a hit of compilation errors in favour of better usage of junit 5 features and correctness.
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/194

Move Junit 5 assertThrows to last statement in lamdba

---

src/main/resources/META-INF/rewrite/assertj.yml
src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionsTest.java

Add recipes for negative variants of startsWith, endsWith, and matches

---

src/main/resources/META-INF/rewrite/mockito.yml
src/test/java/org/openrewrite/java/testing/mockito/MockitoInlineToCoreTest.java

Also upgrade byte buddy during mockito upgrade
If the version of byte-buddy and byte-buddy agent mismatch the mockmaker plugin cannot be initialized
Test coverage
@timtebeek

When upgrading mockito also upgrade potential byte buddy dependencies

---

src/main/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStatic.java
src/main/resources/META-INF/rewrite/mockito.yml
src/test/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStaticTest.java

`Mockito.when` on static (non mock) is no longer allowed with Mockito 4
@timtebeek

Refactor `Mockito.when` on static (non mock) to try with resource

---

src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
src/test/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockitoTest.java

* Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/611
@timtebeek @knutwannheden

`PowerMockitoMockStaticToMockito` should not remove existing `mockStatic` initializer

---

src/main/java/org/openrewrite/java/testing/jmockit/JMockitUtils.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java

IllegalArgumentException generated when running jmockit to mockito recipe on code containing jmockit block VerificationsInOrder, raised here https://github.com/jmockit/jmockit1/issues/729#issuecomment-2406723779
https://javadoc.io/doc/org.jmockit/jmockit/latest/mockit/VerificationsInOrder.html
Stack trace
lang.IllegalArgumentException: No enum constant org.openrewrite.java.testing.jmo
ckit.JMockitBlockType.VerificationsInOrder
[ERROR] java.base/java.lang.Enum.valueOf(Enum.java:273)
[ERROR] org.openrewrite.java.testing.jmockit.JMockitBlockType.valueOf(JMockitB
lockType.java:20)
[ERROR] org.openrewrite.java.testing.jmockit.JMockitUtils.getJMockitBlock(JMoc
kitUtils.java:46)
[ERROR] org.openrewrite.java.testing.jmockit.SetupStatementsRewriter.rewriteMe …

JMockit to Mockito IllegalArumentException No enum constant VerificationsInOrder

---

src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java

Be able to cope with corner cases in refactoring JMockit Verifications.
1. Normally, `anyString` in JMockit should be refactored to `anyString()` in Mockito, so as to `anyInt` or `anyLong`. But when there are redundant `this` before `anyString`, the code will not be processed because OpenWrite treat `anyString` as an `J.Identifier` object where as `this.anyString` as a `J.FieldAccess` object. My patch will do a type cast for this exact case.
2. Normally, `(Object) any` in Mockito should be refactored to `any(Object.class)` in Mockito. This works for simple Object. But when `Object` is an array such as `(byte[]) any`, OpenRewrite will not change it to `any(byte[].class)` because the class type of `byte[]` is not `JavaType.FullyQualified`. I added processing branch for this case. …

Migrate JMockit block to Mockito which contains redundant "this" prefix for arg matcher and migrate array as parameter for any 

---

src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockToMockito.java
src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockType.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitAnnotatedArgumentToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitDelegateToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitExpectationsToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitFullVerificationsToMockitoTest.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitTestBase.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitVerificationsToMockitoTest.java

Migrate JMockit FullVerifications to Mockito
https://www.javadoc.io/doc/org.jmockit/jmockit/latest/mockit/FullVerifications.html
https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html <- for verifyNoMoreInteractions
Replacing FullVerifications with standard mockito verify and then add one line of verifyNoMoreInteractions(mocks. ..)
Also do a refactor of tests to remove some unnecessary code - add a new JMockitTestBase which sets the default parser settings and other tests can inherit from that, hope it's ok to use inhertance here, if not please let me know. I think it makes a lot of sense here.
Just wanted to add this feature to enhance the current migration scope, InOrderVerifications feature was requested here …

Jmockit mockito full verifications and Refactor tests

---

src/main/java/org/openrewrite/java/testing/junit5/MockitoJUnitToMockitoExtension.java
src/test/java/org/openrewrite/java/testing/mockito/MockitoJUnitToMockitoExtensionTest.java

In previous PR, I forgot to include a default if the tests where not using silent or strictness calls. 
Went for WARN as default as that's the default in junit4, and other wise junit5 would start failing on these tests.

Added default warn strictness if no strictness modifiers are used.

---

src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
src/test/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertionTest.java

SimplifyChainedAssertJAssertion drops method calls in replacement

---

src/main/java/org/openrewrite/java/testing/mockito/VerifyZeroToNoMoreInteractions.java
src/main/resources/META-INF/rewrite/mockito.yml
src/test/java/org/openrewrite/java/testing/mockito/VerifyZeroToNoMoreInteractionsTest.java

Extra recipe to migration the `verifyZeroInteractions` method for older Mockito versions:
> If coming from Mockito < 3 then change from verifyZeroInteractions to verifyNoMoreInteractions
if coming from Mockito 3+ then change from verifyZeroInteractions to verifyNoInteractions (as we do now)
- fixes #630

Add `VerifyZeroToNoMoreInteractions` for Mockito 2

---

src/main/java/org/openrewrite/java/testing/mockito/SimplifyMockitoVerifyWhenGiven.java
src/test/java/org/openrewrite/java/testing/mockito/SimplifyMockitoVerifyWhenGivenTest.java

- fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/634
Added a test for [issue #634](https://github.com/openrewrite/rewrite-testing-frameworks/issues/634)
Added handling of org.mockito.Mockito.eq(..) when simplifying mockito matchers
We are using `import static org.mockito.Mockito.*;` at my company, and in its current state this recipe does not support it.

Added handling of org.mockito.Mockito.eq(..) when simplifying mockito matchers

---

src/main/java/org/openrewrite/java/testing/assertj/AdoptAssertJDurationAssertions.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertFalseToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertInstanceOfToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotEqualsToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotNullToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNullToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertSameToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertTrueToAssertThat.java
src/main/java/org/openrewrite/java/testing/assertj/JUnitFailToAssertJFail.java
src/main/java/org/openrewrite/java/testing/assertj/SimplifyAssertJAssertion.java
src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java

The AssertJ recipes use an older recipe code style; replaced all of 'm with an anonymous class + remove boilerplate code. The class `JUnitAssertInstanceOfToAssertThat` (created in https://github.com/openrewrite/rewrite-testing-frameworks/pull/606) i is used as the base template for all changed recipes.
Code convergence
Recipes in other packages I have left out of the scope of this PR. For example, the cleanup recipes also use the “old” recipe style.

Update AssertJ recipes to current recipe code style

---

src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java

JUnit5 migration recipe
I have an application that uses Testcontainers junit-jupiter
We don't want to exclude JUnit4 because Testcontainers needs it.

don't exclude junit4 for testcontainers jupiter

---

src/main/java/org/openrewrite/java/testing/junit5/UseAssertSame.java
src/test/java/org/openrewrite/java/testing/junit5/UseAssertSameTest.java

Adding a new recipe for converting:
```
assertTrue(a == b);
```
to
```
assertSame(a, b);
```
for JUnit5 test code as suggested in 
- #260

Use JUnit5's `assertSame` or `assertNotSame` instead of `assertTrue(... == ...)`

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrder.java
src/test/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrderTest.java

- fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/636
Added support for Junit 4 matchers in the `AssertionsArgumentOrder` recipe : 
- assertEquals
- assertNotEquals
- assertSame
- assertNotSame
Junit 5 migration is sometimes complicated so supporting Junit 4 is a plus.
Did not add support for assertIterableEquals (does not exist in Junit 4), for assertArrayEquals and assertNull as the signature differs from Junit 5.

Add support for Junit 4 matchers on AssertionsArgumentOrder

---

build.gradle.kts
src/main/resources/META-INF/rewrite/htmlunit.yml
src/test/java/org/openrewrite/java/testing/htmlunit/UpgradeHtmlUnit3Test.java

Moved here from rewrite-jenkins, with improvements to the test setup, and additional change dependency recipes
- Needed for https://github.com/openrewrite/rewrite-spring/issues/627

Move HtmlUnit migrations to rewrite-testing-frameworks

---

src/main/resources/META-INF/rewrite/hamcrest.yml
src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java

Flipped around when we add the dependency, as we saw it needlessly added, and to the wrong Gradle configuration.

Add AssertJ dependency if using Hamcrest

---

build.gradle.kts
src/test/java/org/openrewrite/java/testing/mockito/Mockito1to4MigrationTest.java

add unit test for Mockito1to4Migration
Motivation:  I could not find a unit test for Mockito1to4Migration

add Mockito1to4MigrationTest

---

build.gradle.kts
src/main/java/org/openrewrite/java/testing/assertj/IsEqualToIgnoringMillisToIsCloseTo.java
src/main/resources/META-INF/rewrite/assertj.yml
src/test/java/org/openrewrite/java/testing/assertj/IsEqualToIgnoringMillisToIsCloseToTest.java

This adds a recipe to replace `org.assertj.core.api.AbstractDateAssert.isEqualToIgnoringMillis(java.util.Date)` by the proposed method `isCloseTo()`
New refaster recipe `java/org/openrewrite/java/testing/assertj/IsEqualToIgnoringMillisToIsCloseTo.java`
closes#653
The recipe is not working yet as expected. It should add a static import for the method, but does not.
Not sure what I should test as negative case here.
@timtebeek

Add recipe for replacing deprecated method AbstractDateAssert

---

src/test/java/org/openrewrite/java/testing/mockito/Mockito1to5MigrationTest.java

new unit test:   Mockito1to5MigrationTest.java
Motivation:  I could not find a unit test for Mockito1to5Migration

Add `Mockito1to5MigrationTest` to verify dependencies are upgraded

---

src/main/resources/META-INF/rewrite/mockito.yml

`org.openrewrite.java.testing.mockito.Mockito1to3Migration` added `org.mockito:mockito-junit-jupiter:3.x` in runtime scope which is pretty dangerous.

Add `org.mockito:mockito-junit-jupiter:3.x` in explicit test scope

---

src/main/java/org/openrewrite/java/testing/search/FindUnitTestTable.java
src/main/java/org/openrewrite/java/testing/search/FindUnitTests.java
src/main/java/org/openrewrite/java/testing/search/package-info.java
src/main/java/org/openrewrite/java/testing/table/FindUnitTestTable.java
src/test/java/org/openrewrite/java/testing/search/FindUnitTestsTest.java

Adding a recipe to find examples of how a method is being used in unit tests.
This recipe can then be used for rewrite-comprehension to feed more information to an LLM.

Feat find unit tests

---

src/main/java/org/openrewrite/java/testing/search/FindUnitTests.java
src/main/java/org/openrewrite/java/testing/search/UnitTest.java

Adding access to accumulator for the recipe FindUnitTest, such that rewrite-comprehension may use the recipe to augment the information being supplied to an LLM.

Feat add access to acc ai rewrite comprehension

---

src/main/resources/META-INF/rewrite/junit5.yml
src/main/resources/META-INF/rewrite/mockito.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
src/test/java/org/openrewrite/java/testing/testng/TestNgToAssertJTest.java

Add `mockito-junit-jupiter`dependency 
https://github.com/openrewrite/rewrite-testing-frameworks/blob/6aa80c958f3fc0d0c9954c7a24dd0481fe49eb83/src/main/resources/META-INF/rewrite/mockito.yml#L171-L177 expected to handle `@MockitoExtension` didn't work because `AddDependency` is a scanning recipe and scanning for `org.mockito.junit.jupiter.*` is performed before the package is added on `editSources` phase by [RunnerToExtension](https://github.com/openrewrite/rewrite-testing-frameworks/blob/6aa80c958f3fc0d0c9954c7a24dd0481fe49eb83/src/main/resources/META-INF/rewrite/junit5.yml#L201)
Now `onlyIfUsing` is looking for the initial runners that are present on the `scanSources` phase. 
**Note:** if the old version of recipe is ran in two cycles then it adds `mockito-junit-jupiter` dependency in …

Add mockito-junit-jupiter when using runner in JUnit 4

---

src/main/java/org/openrewrite/java/testing/junit5/AddMissingNested.java
src/test/java/org/openrewrite/java/testing/junit5/AddMissingNestedTest.java

Do not _nest_ an inner `@interface` class.
When using annotation composition (as an inner class of a test class), the `AddMissingNested` recipe is nesting that inner class. That is not correct.
yes, excluding a _child_ recipe but according to several discussions that is and will not be supported.

No `@Nested` for inner composed annotation

---

src/main/java/org/openrewrite/java/testing/mockito/NoInitializationForInjectMock.java
src/test/java/org/openrewrite/java/testing/mockito/NoInitializationForInjectMockTest.java

The `NoInitializationForInjectMock` recipe removes unnecessary initializers for fields that have already been marked with the `@InjectMocks` annotation. However, a compile error will occur if that field is currently final since it sees an uninitialized field. The recipe has been modified to remove the final modifier to remedy this.
Take the following code:
```java
@InjectMocks
final MyObject myObject = new MyObject("someField");
```
Applying the current recipe yields
```java
@InjectMocks
final MyObject myObject; // Does not compile
```
Applying the modified recipe yields
```java
@InjectMocks
MyObject myObject;
```
Alternatively, you might consider skipping any final fields instead or adding an option to choose the behavior.

Fix final field `@InjectMock` recipe

---

src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
src/test/java/org/openrewrite/java/testing/jmockit/JMockitMockUpToMockitoTest.java
src/test/java/org/openrewrite/java/testing/junit5/UpgradeOkHttpMockWebServerTest.java
src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java

Previously we saw these imports removed. The type information is actually present for these methods, meaning the old logic was perhaps not working as well as it should have.

Retain Mockito Kotlin `whenever` as needed

---

src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoWhenNewToMockito.java
src/main/resources/META-INF/rewrite/powermockito.yml
src/test/java/org/openrewrite/java/testing/mockito/ReplacePowerMockitoIntegrationTest.java

Adding support to `ReplacePowerMockito` for dealing with constructor mocking using `PowerMockito.whenNew` in the **simplest case** only - i.e. when using no arguments constructor.
The plan is to have another PR for constructors with arguments.
To address one of the customers' feedback.
Related:#646

ReplacePowerMockito to support `PowerMockito.whenNew` constructor mocking - the simplest case

---

src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoWhenNewToMockito.java
src/test/java/org/openrewrite/java/testing/mockito/ReplacePowerMockitoIntegrationTest.java

Continuation of #684.
Enhancing the support for `PowerMockitoWhenNewToMockito` recipe for mocking constructors other than 0-arg ones (as #684 did).
To address one of the customers' feedback.
Yes! I am glad you are asking:
As submitted the code will **ignore** the actual mocked constructor arguments, resulting in mocking all creations of objects of given class. As opposed to only some, i.e. these whose arguments matched. This is because based on my research, I couldn't find any direct counterpart of input like `.withArguments("param1", 3)`.
The reason I think ignoring the arguments is that I think typically you are interested in mocking just one call to the constructor. And even if you are interested in multiple calls. This is still **possible** with the code given. You mock one class, and …

Supporting arguments in PowerMockitoWhenNewToMockito

---

src/main/resources/META-INF/rewrite/assertj.yml
src/test/java/org/openrewrite/java/testing/assertj/StaticImportsTest.java

- Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/664
Pending the possible adoption of `.assertThatClass` or `.assertThatInterface` in AssertJ.
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/664#issuecomment-2600958012

Do not `ChangeMethodTargetToStatic` for AssertJ's `AssertionsFor...Types`

---

src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
src/main/java/org/openrewrite/java/testing/junit5/TestRuleToTestInfo.java
src/main/java/org/openrewrite/java/testing/junit5/TimeoutRuleToClassAnnotation.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateMockWebServer.java
src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/main/java/org/openrewrite/java/testing/junit5/UseTestMethodOrder.java
src/main/java/org/openrewrite/java/testing/mockito/MockitoJUnitRunnerSilentToExtension.java
src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/EnclosedToNestedTest.java
src/test/java/org/openrewrite/java/testing/junit5/TimeoutRuleToClassAnnotationTest.java

Created a new recipe for migrating `@Rule Timeout` test class variable to JUnit 5 `@Timeout` class annotation

Recipe to replace @Rule Timeout to JUnit 5 Timeout annotation

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java

Added support to the `JUnitAssertThrowsToAssertExceptionType` recipe for retaining descriptions.
The `assertThrows` has overloads with 3 parameters, the last parameter being a message to display on failure, which is not currently supported.
I couldn't get the tests to work when I included the types within the `#{any()}` as was done within the existing code, the tests would then fail with an error of the form  
`/*~~(MethodInvocation type is missing or malformed)~~>*/assertThatExceptionOfType(NullPointerException.class).as("message").isThrownBy(() -> foo())`  
that I wasn't knowledgable enough to get to the bottom of.

Convert JUnit AssertThrows with description message over to AssertJ

---

.github/workflows/stale.yml

Adding stale workflow for closing stale PRs with no activity in 90 days.
Note: this does **not** touch issues. They should stay!
To keep the PR queue clean.
- https://github.com/actions/stale

Adding stale workflow

---

src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
src/test/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionTypeTest.java

Allow for JUnit AssertThrows assertions that use the returned value to be converted to the AssertJ equivalent with AssertThatExceptionOfType.
When this conversion was causing an issue, as resolved by #331, the decision was made to ignore conversions of assertions that used the return value due to no functional equivalent being available in AssertJ.  
Since then AssertJ has released [v3.27.0](https://github.com/assertj/assertj/releases/tag/assertj-build-3.27.0) which has introduced the [`actual`](https://www.javadoc.io/doc/org.assertj/assertj-core/3.27.0/org/assertj/core/api/AbstractAssert.html#actual()) method which allows the retrieval of the actual value. This can be used to ensure that functionality can be replicated, although ideally any subsequent assertions of the exception would be …

Convert JUnit AssertThrows with assigment over to AssertJ

---

src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
src/test/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterizedTest.java

Fixed a bug in the JUnitParamsRunnerToParameterized recipe that incorrectly converted regular tests to @ParameterizedTest if the test class contained any @ParameterizedTest annotations.

Fix: Don't modify regular test to parameterized test incorrectly

---

src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
src/test/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterizedTest.java

In JUnit4, parameterized tests populate class fields before executing the @Before method, allowing setup logic to rely on those values. However, in JUnit5, @ParameterizedTest methods receive arguments directly, and the test instance is created before those values are available. As a result, there is no lifecycle hook where the arguments can be injected before @BeforeEach runs.
This mismatch breaks any setup logic that depends on parameter-initialized fields.
To preserve behavior consistent with JUnit4, this change manually invokes the setup method after setting the parameter values to the class fields inside the test method. This ensures any logic in @BeforeEach continues to function correctly with the parameter values in place.
Invoke the setup method if it references or depends on the …

Fix ParameterizedRunnerToParameterized recipe: Preserve field-dependent setup logic

---

src/main/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMock.java
src/main/resources/META-INF/rewrite/examples.yml
src/main/resources/META-INF/rewrite/junit5.yml
src/main/resources/META-INF/rewrite/mockito.yml
src/test/java/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.java
src/test/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMockTest.java

If the test class contains mocks initialization 
```java
@BeforeEach
public void setUp() {
// ...
MockitoAnnotations.initMocks(this);
// ...
}
```
it should be replaced and extended in the following way:
```java
private AutoCloseable mocks;
@BeforeEach
public void setUp() {
// ...
mocks = MockitoAnnotations.openMocks(this);
// ...
}
@AfterEach
public void tearDown() throws Exception {
// ...
mocks.close();
// ...
}
```

Recipe to replace `initMocks` with `openMocks`

---

src/main/java/org/openrewrite/java/testing/mockito/MockitoJUnitRunnerSilentToExtension.java
src/main/java/org/openrewrite/java/testing/mockito/MockitoJUnitRunnerToExtension.java
src/test/java/org/openrewrite/java/testing/mockito/MockitoJUnitRunnerToExtensionTest.java

Created a Recipe to migrate MockitoJUnitRunner to MockitoExtension. 
The previous implementation had few issues:
1. It only handled lenient and warn modes, and incorrectly migrated warn mode to strict mode (while the default for MockitoJUnitRunner is warn, the default for MockitoExtension is strict).
2. Mode-specific handling was split between imperative (for lenient) and declarative (for warn) recipes.
1. Consolidated all mode-handling logic (strict, warn, and lenient) into a single imperative recipe.
2. New recipe correctly maps warn mode to maintain expected behavior and also handled strict mode for MockitoJUnitRunner.
3. Marked the previous imperative recipe as deprecated for backward compatibility instead of removing it.
I will create a followup PR to update the UseMockitoExtension …

Implement MockitoJUnitRunner to Extension Recipe

---

src/main/java/org/openrewrite/java/testing/junit5/MockitoJUnitToMockitoExtension.java
src/test/java/org/openrewrite/java/testing/mockito/MockitoJUnitToMockitoExtensionTest.java

The MockitoJUnitToMockitoExtension recipe was not importing mockito-core as a resource, which caused missing type attribution for Mockito-related expressions generated by the Java template parser. Previously, tests passed because the maybeAddImport method was used with onlyReferenced = false, masking the issue.
To fix this, imported mockito-core for corresponding JavaTempalteParser.
To verify the fix, updated the maybeAddImport method to use onlyReferenced = true and confirmed that mockito related imports being added.

Fix Import of Mockito classes in MockitoRuleToExtension recipe

---

src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
src/main/resources/META-INF/rewrite/examples.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5BestPracticesTest.java
src/test/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.java

The TemporaryFolderToTmpDir recipe incorrectly migrates `temporaryFolder.newFile(fileName)` to `Files.createTempFile(fileName, null, temporaryFolder)`. This approach changes the behavior: instead of creating a file with the exact name fileName, it uses fileName as a prefix and appends random characters as a suffix.
To address this, introduced a new newFile method that correctly replicates the original behavior. This method creates a File instance with `new File(temporaryFolder, fileName)` which is identical to `temporaryFolder.newFile` method.
**Note**: I didn't touch the `temporaryFolder.newFile` without arguments as internally translates to `Files.createTempFile`
Additionally, the migration now updates all occurrences of temporaryFolder.newFile(fileName) to use the new newFile(fileName) …

Fix Incorrect Migration of TemporaryFolder.newFile in TemporaryFolderToTmpDir Recipe

---

src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
src/test/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterizedTest.java

The JUnitParamsRunnerToParameterized recipe updates the test method to static as required by JUnit 5, but it only updates the source method itself. If that method references other non-static methods, it leads to compilation failures.
This fix recursively identifies and updates all transitive method references that need to be static.
Before fix
```
private static Object[] youngAdultPersonParams() {
return new Object[]{new Object[]{getAge(2000), false}, new Object[]{getAge(2005), false}};
}
private int getAge(int birthYear) {
return getCurrentYear() - birthYear;
}
private int getCurrentYear() {
return LocalDateTime.now().getYear();
}
```
After fix
```
private static Object[] youngAdultPersonParams() {
return new Object[]{new Object[]{getAge(2000), false}, new Object[]{getAge(2005), false}}; …
```

Fix JunitParams to Parameterized by recursively updating referenced method to static

---

src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
src/test/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterizedTest.java

ParameterizedRunnerToParameterized recipe converts constructor to initMethod but it may have redundant super call, this fix removes that redundant super call.

Fix ParameterizedRunnerToParameterized: Remove redundant super call

---

src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
src/main/resources/META-INF/rewrite/examples.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5BestPracticesTest.java
src/test/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.java

The TemporaryFolderToTempDir recipe did not correctly handle TemporaryFolder instances that were not annotated with @Rule.
Issue: When the recipe made other changes, the ChangeType incorrectly migrates `new TemporaryFolder()` to `new File()`.
This PR updates the recipe to properly handle TemporaryFolder instances that are not explicitly annotated with @Rule,

Handle non-@Rule TemporaryFolder fields

---

src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
src/test/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.java

The TemporaryFolderToTempDir recipe was previously adding newFolder and newFile methods to all classes in the compilation unit and this may produce uncompilable code. The updated code now adds these methods only to the relevant class.
Before
```
class MyTest {
@Rule
TemporaryFolder tempDir1 = new TemporaryFolder();
void foo() throws IOException {
File file1 = tempDir1.newFolder();
}
class InnerClass {
private static File newFolder(File root, String... subDirs) throws IOException {}
}
private static File newFolder(File root, String... subDirs) throws IOException { }
}
```
After
```
class MyTest {
@Rule
TemporaryFolder tempDir1 = new TemporaryFolder();
void foo() throws IOException {
File file1 = tempDir1.newFolder();
}
class InnerClass { }
private static File newFolder(File root, String... …
```

Fix TemporaryFolderToTempDir: Don't add methods to unrelated classes

---

src/main/java/org/openrewrite/java/testing/easymock/EasyMockVerifyToMockitoVerify.java
src/main/java/org/openrewrite/java/testing/hamcrest/AssertThatBooleanToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestNotMatcherToAssertJ.java
src/test/java/org/openrewrite/java/testing/easymock/EasyMockVerifyToMockitoVerifyTest.java
src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestOfMatchersToAssertJTest.java
src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java
src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java

PR [#5439](https://github.com/openrewrite/rewrite/pull/5439) introduced logic to detect and handle import ambiguity when adding imports. However, this caused some tests to fail due to the order in which imports were being added and removed in some recipes. When new imports were added before the old ones were removed, this led to false positives for ambiguity, resulting in the use of fully qualified names.
This PR addresses the issue by reordering the maybeAddImport and maybeRemoveImport call. Now maybeRemoveImport precedes the maybeAddImport, to avoid premature ambiguity detection. 
Additionally, some unit tests contained genuinely ambiguous imports that went undetected earlier. Fixed those test to align with the improved import resolution logic.

Fix import ambiguity regression by reordering AddImport/RemoveImport

---

src/main/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMock.java
src/test/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMockTest.java

This pr updates the ReplaceInitMockToOpenMock recipe to avoid creating duplicate tearDown methods. Previously, the recipe would unconditionally add a tearDown method, potentially causing conflicts if one already existed in the class. The new logic checks for existing methods named tearDown and appends the next available numeric suffix (e.g., tearDown0, tearDown1, etc.) to ensure method name uniqueness.

ReplaceInitMockToOpenMock: Ensure unique name for added tearDown method

---

src/main/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOf.java
src/test/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOfTest.java

Added support for generic instanceof checks in `AssertTrueInstanceofToAssertInstanceOf` recipe
The recipe threw parsing errors.
I've changed the recipe to support `assertTrue(list instanceof List<?>);` and change it to `assertInstanceOf(List.class, list);`.
Another option would be to ignore the breaking instance check, but I don't think the generic has any functional meaning.

Added support for generic instanceof checks in `AssertTrueInstanceofToAssertInstanceOf` recipe

---

src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java

Bumping xmlunit in one of the test cases.
Fix broken CI:
```
-      <version>2.10.1</version>	
+      <version>2.10.2</version>
```

xmlunit 2.10.2

---

src/main/resources/META-INF/rewrite/junit5.yml
src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java

Instead of adding the JUnit 4 exclusion to all dependencies and then removing it from specific ones that depend on Testcontainers, just don’t add the exclusion when Testcontainers is used.
We have implemented some test libraries that (transitively) depend on Testcontainers. When (indirectly) running the JUnit 5 migration recipe, it always adds the junit exclusion on those, which breaks the build. This forces us to un-exclude JUnit 4 as a followup recipe.
Current workaround is to remove the exclusion explicitly for all dependencies after JUnit 5 migration:
```yml
- org.openrewrite.maven.RemoveExclusion:
groupId: '*'
artifactId: '*'
exclusionGroupId: junit
exclusionArtifactId: junit
```
This makes the recipe more conservative. If a project transitively depends on Testcontainers, it won’t …

Do not ever exclude junit if Testcontainers is used

---

src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNull.java
src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNull.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.recipes.IsLiteralNullRecipe?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw

refactor: Adopt `J.Literal.isLiteralValue(expression, null)`

---

src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java

Bumping the xmlunit-legacy version to `2.10.3` in one of the tests.
CI is failing:
```
UseXMLUnitLegacyTest > shouldMigrateMavenDependency() FAILED
```
after https://central.sonatype.com/artifact/org.xmlunit/xmlunit-legacy/2.10.3 got released.

xmlunit 2.10.3

---

src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
src/test/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotationTest.java

When transforming `@Test(expected = SomeException.class)` to JUnit 5's `assertThrows()`, the recipe now preserves throws clauses for exceptions other than the one being tested.
Changes made:
- Modified `UpdateTestAnnotation` to selectively remove only the exception type being tested from the throws clause
- Added logic to identify and preserve other declared exceptions in the method signature
- Added test case to verify throws clauses are preserved for non-tested exceptions
The fix ensures that methods declaring multiple thrown exceptions maintain proper signatures after transformation.
Fixes:
- #754

Fix for JUnit test method throws clause preservation

---

src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
src/test/java/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.java

Disabled `CleanupMockitoImports` for Kotlin
There were reports method invocations like `any` and `eq` were not found for Kotlin code, thus it's better to disable the clean up step.
Later on, we can go back to this recipe to properly enable Kotlin support again.

Don't clean up mockito imports for Kotlin

---

src/main/java/org/openrewrite/java/testing/mockito/MockitoJUnitRunnerToExtension.java
src/test/java/org/openrewrite/java/testing/mockito/MockitoJUnitRunnerToExtensionTest.java

This PR updates the MockitoJUnitRunnerToExtension recipe to better handle the migration from MockitoJUnitRunner to MockitoExtension. Specifically:
- It now checks for the presence of an existing @ExtendWith(MockitoExtension.class) annotation to avoid adding duplicates.
- It verifies the configured strictness level, and only updates it if the existing level is more restrictive than what JUnit 4's runner.
In some cases a developer may have bothe MockitoRule and MockitoJunitRunner both in same test class. In that case the MockitoJUnitToMockitoExtension and MockitoJUnitRunnerToExtension both tries to add `MockitoExtension` or `MockitoSettings` which is not repeatable and test fails with compilation error. Updated MockitoJUnitRunnerToExtension to not add these extension if one already exists, …

MockitoJUnitRunnerToExtension: Handle existing MockitoExtension

---

src/main/resources/META-INF/rewrite/junit6.yml

From the release notes:
> The lineSeparator attribute in `@CsvFileSource` has been removed. The line separator is now automatically detected, meaning that any of `\r`, `\n`, or `\r\n` is treated as a line separator.

Remove lineSeparator annotation attribute

---

src/main/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStatic.java
src/test/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStaticTest.java

- Follow-on to https://github.com/openrewrite/rewrite-testing-frameworks/pull/798
In the same places where `MockitoWhenOnStaticToMockStatic` is detecting `@Before` and `@BeforeClass` for JUnit, it will now be able to detect the equivalent TestNG versions.

Adding support for recognizing instantiation of mocked static in TestNG-related `@BeforeMethod` and `@BeforeClass` annotated methods

---

src/test/java/org/openrewrite/java/testing/junit5/UseXMLUnitLegacyTest.java

Changing the expected version in the `UseXMLUnitLegacyTest` test.
Likely after a new release of said library.
Fix broken CI.

`UseXMLUnitLegacyTest` to expect xmlunit 2.10.4
