- .github/workflows/ci.yml
- build.gradle.kts
https://github.com/openrewrite/rewrite/issues/324
> skip snapshot gpg signing by default unless opt-in

- src/test/kotlin/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.kt
See: https://github.com/openrewrite/rewrite-testing-frameworks/issues/72
Single test slapped together for assertThrows with a `matcher` of an error message.
Don't take this as definitive truth, it's just something I put together in the morning, and it was suggested to have this merged in but with the `Disabled` annotation.
Put together based on https://github.com/junit-team/junit5/issues/- 2154 and https://github.com/junit-team/junit5/issues/ - 2128 (separating issue numbers to prevent linking)
I'm not 100% sure, this was done in passing, but based on this information, it's possible that `expectedException` should actually be using a separate `assertThat` or `assertTrue` rather than a custom message as the final argument to the lambda.
> Test for assertThrows with message matcher

- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/resources/META-INF/rewrite/junit5.yml
Add ParameterizedRunnerToParameterized to JUnit4To5Migration and some polish
> Add ParameterizedRunnerToParameterized to JUnit4To5Migration and some polish

- build.gradle.kts
- src/jmh/.gitignore
- src/jmh/java/org/openrewrite/benchmarks/java/JavaCompilationUnitState.java
- src/jmh/java/org/openrewrite/benchmarks/java/UpdateTestAnnotationBenchmark.java
scaffolding for jmh benchmarking prior to making performance improvements, based on prometheus execution timing data
> jmh benchmark scaffolding and baseline UpdateTestAnnotationBenchmark

- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
decomposing into smaller visitors for discrete data in grafana. this is reversible.
> UpdateTestAnnotations performance evaluation trial

- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
Reverts openrewrite/rewrite-testing-frameworks#98
only for the sake of keeping a/b delta together-- will merge all this back in...
> Revert "UpdateTestAnnotations performance evaluation trial"

- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
Without FindType check for performance comparison. This should be be good enough to roll.
> UpdateTestAnnotations performance evaluation trial v2

- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
> UpdateTestAnnotations perf. improvements

- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertFalseToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertNotEqualsToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertNotNullToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertNullToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertSameToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitAssertTrueToAssertThatTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/JUnitFailToAssertJFailTest.kt
- src/test/kotlin/org/openrewrite/java/testing/assertj/StaticImportsTest.kt
mostly just pulling back indentation
> formatting polish in assertj test package

- src/test/kotlin/org/openrewrite/java/testing/mockito/CleanupMockitoImportsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.kt
- src/test/kotlin/org/openrewrite/java/testing/mockito/MockUtilsToStaticTest.kt
mostly just pulling back indentation
> formatting polish in mockito tests

- src/test/kotlin/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/AssumeToAssumptionsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/CategoryToTagTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/CleanupJUnitImportsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/RemoveObsoleteRunnersTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/StaticImportsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDirTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotationsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/junit5/UseTestMethodOrderTest.kt
mostly just pulling back indentation
> formatting polish in junit tests

- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/junit5/CleanupJUnitImports.java
- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/RemoveObsoleteRunners.java
- src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotations.java
- src/main/java/org/openrewrite/java/testing/junit5/UseTestMethodOrder.java
- src/test/kotlin/org/openrewrite/java/testing/BeforeToAfter.kt
minor indentation and spacing formatting using default autoformat
> miscellaneous indentation and formatting polish

- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertFalseToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotNullToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNullToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertSameToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertTrueToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitFailToAssertJFail.java
- src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
- src/main/java/org/openrewrite/java/testing/junit5/CategoryToTag.java
- src/main/java/org/openrewrite/java/testing/junit5/CleanupJUnitImports.java
- src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotations.java
- src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
- src/main/java/org/openrewrite/java/testing/mockito/MockUtilsToStatic.java
* make isFloatingPointType static
* replace lambdas with method references
* make ParameterizedRunnerToParameterizedTestsVisitor static
* make methods such as isJunitAssertMethod and isFloatingPoint static methods
* use isEmpty in place of greater than zero
* make inner runner static
* fix MockitoStaticImport lambda J dot
* MockUtilsToStatic method matcher private static final, fix description
* CleanupMockitoImports add punctuation to description
* reformat descriptions to have capitalized first letter, punctuation at the end, and replace any escaped quotation marks with backticks
> Polishing commits

- build.gradle.kts
- src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
- src/test/kotlin/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrowsTest.kt
Refactor the recipe to work with general uses of the ExpectedException class.
fixes #72
> Refactor expected exception recipe - fixes #72

- build.gradle.kts
- src/main/java/org/openrewrite/java/testing/junit5/MockitoJUnitToMockitoExtension.java
- src/main/resources/META-INF/rewrite/junit5.yml
- src/test/kotlin/org/openrewrite/java/testing/junit5/MockitoJUnitToMockitoExtensionTest.kt
fixes #86 
Added MockitoRule recipe.
> Add MockitoRule recipe.

- src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
- src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateMockWebServer.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
- src/test/kotlin/org/openrewrite/java/testing/junit5/MigrateJunitTestCaseTest.kt
- src/test/kotlin/org/openrewrite/java/testing/mockito/JunitMockitoUpgradeIntegrationTest.kt
A PR to support changes made in rewrite-core for parameterized types.
> Parameterized types

- src/main/resources/META-INF/rewrite/AssertJAssertions.java
Update the AssertJAssertions template for all use cases.  Fixes #133
> Update AssertJAssertions template

- src/main/java/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotations.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
See https://github.com/openrewrite/rewrite/issues/622
> Use ChangeMethodAccessLevelVisitor

- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotations.java
Co-authored-by: Moderne <team@moderne.io>
🐕🌯
> refactor: format java code

- src/main/java/org/openrewrite/java/testing/junit5/RemoveObsoleteRunners.java
- src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
- src/main/java/org/openrewrite/java/testing/mockito/MockUtilsToStatic.java
Co-authored-by: Moderne <team@moderne.io>
> refactor: Automate fixing Sonar issues.

- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertNotEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
- src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
- src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
Co-authored-by: Moderne <team@moderne.io> 
polish
> refactor: Code cleanup

- src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseEqualsToAssertNotEquals.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueEqualsToAssertEquals.java
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertFalseEqualToAssertNotEqualsTest.kt
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertTrueEqualToAssertEqualsTest.kt
> add AssertFalseEqualsToAssertNotEquals and AssertTrueEqualsToAssertEquals

- src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseNegationToAssertTrue.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNegationToAssertFalse.java
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertFalseNegationToAssertTrueTest.kt
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertTrueNegationToAssertFalseTest.kt
> add recipes AssertFalseNegationToAssertTrue and AssertTrueNegationToAssertFalse

- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueComparisonToAssertEquals.java
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertTrueComparisonToAssertEqualsTest.kt
> add recipe AssertTrueComparisonToAssertEquals

- src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNull.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNull.java
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertFalseNullToAssertNotNullTest.kt
- src/test/kotlin/org/openrewrite/java/testing/cleanup/AssertTrueNullToAssertNullTest.kt
> add recipes AssertFalseNullToAssertNotNull and AssertTrueNullToAssertNull

- src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java
- src/test/kotlin/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertionsTest.kt
Changes:
- Added optional comma delimited list of additional asserts to detect method invocations outside of the project or class.
- Check method bodies in the class for asserts.
fixes #201
> Do not wrap methods with invocations that contain asserts in the class or specified in optional list.

- src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
- src/test/kotlin/org/openrewrite/java/testing/junit5/MigrateJUnitTestCaseTest.kt
> Migrate junit.framework.Assert

- src/main/resources/META-INF/rewrite/junit5.yml
[As suggested here](https://github.com/apache/maven-wrapper/pull/61#pullrequestreview-1084485426).
> Add dependency on JUnit Jupiter (Aggregator) only, not api + engine

- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertArrayEqualsToAssertThat.java
- src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java
- src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldIncludeAssertions.java
- src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublic.java
- src/main/java/org/openrewrite/java/testing/cucumber/CucumberJava8HookDefinitionToCucumberJava.java
- src/main/java/org/openrewrite/java/testing/junit5/AddMissingNested.java
- src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
- src/main/java/org/openrewrite/java/testing/junit5/CategoryToTag.java
- src/main/java/org/openrewrite/java/testing/junit5/MockitoJUnitToMockitoExtension.java
- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/RemoveObsoleteRunners.java
- src/main/java/org/openrewrite/java/testing/junit5/RunnerToExtension.java
- src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateMockWebServer.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
- src/main/java/org/openrewrite/java/testing/junit5/UseTestMethodOrder.java
* There are no JUnit4 and JUnit5, they are "JUnit 4" and "JUnit 5".
* AssertJ with uppercase A
> Fix some framework names and typos

- src/main/java/org/openrewrite/java/testing/assertj/UseExplicitContains.java
- src/main/java/org/openrewrite/java/testing/assertj/UseExplicitSize.java
- src/main/resources/META-INF/rewrite/assertj.yml
- src/test/java/org/openrewrite/java/testing/assertj/UseExplicitSizeTest.java
This recipe transform assertThat(collection.size()).isEqualTo(1); into assertThat(collection).hasSize(1);
I have also added this and the other assertj recipe to the assertj.yml file.
> Added recipe for size

- src/main/resources/META-INF/rewrite/junit5.yml
> Use Vert.x

- src/main/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOf.java
Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/403
(No long explanation - I can add if desired)
> Remove System.out.println

- src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestIsMatcherToAssertJ.java
- src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
- src/main/resources/META-INF/rewrite/hamcrest.yml
- src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJTest.java
- src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/468
> Limit Hamcrest replacements by type

- src/main/resources/META-INF/rewrite/junit5.yml
- src/test/java/org/openrewrite/java/testing/junit5/JUnit5MigrationTest.java
Fixes #477 
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/477
Similar to 
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/430
> Also remove exclusion from spring-boot-testcontainers

- src/main/java/org/openrewrite/java/testing/junit5/AssertToAssertions.java
- src/test/java/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.java
> AssertToAssertions should only convert methods from exact class

- src/main/resources/META-INF/rewrite/hamcrest.yml
- src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToAssertJTest.java
> Migrate all Hamcrest matchers from core package

- src/main/java/org/openrewrite/java/testing/assertj/SimplifyAssertJAssertion.java
Should be quicker due to caching of templates.
> Context free SimplifyAssertJAssertion

- src/main/resources/META-INF/rewrite/mockito.yml
- src/main/resources/META-INF/rewrite/powermockito.yml
- src/test/java/org/openrewrite/java/testing/mockito/RemoveMockitoSettingsTest.java
- https://github.com/openrewrite/rewrite-testing-frameworks/issues/360
- https://github.com/openrewrite/rewrite-testing-frameworks/commit/7999511a3cf4e61c54b4aba2b674416cc24ddbc1
> Include `ReplacePowerMockito` with `Mockito1to3Migration` again

- src/main/java/org/openrewrite/java/testing/assertj/JUnitAssertThrowsToAssertExceptionType.java
- src/main/java/org/openrewrite/java/testing/assertj/SimplifyChainedAssertJAssertion.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertEqualsBooleanToAssertBoolean.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseEqualsToAssertNotEquals.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertNotEqualsBooleanToAssertBoolean.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueComparisonToAssertEquals.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueEqualsToAssertEquals.java
- src/main/java/org/openrewrite/java/testing/cleanup/RemoveTestPrefix.java
- src/main/java/org/openrewrite/java/testing/cleanup/SimplifyTestThrows.java
- src/main/java/org/openrewrite/java/testing/cleanup/TestsShouldNotBePublic.java
- src/main/java/org/openrewrite/java/testing/jmockit/ArgumentMatchersRewriter.java
- src/main/java/org/openrewrite/java/testing/jmockit/SetupStatementsRewriter.java
- src/main/java/org/openrewrite/java/testing/junit5/AssertTrueInstanceofToAssertInstanceOf.java
- src/main/java/org/openrewrite/java/testing/junit5/EnclosedToNested.java
- src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
- src/main/java/org/openrewrite/java/testing/junit5/GradleUseJunitJupiter.java
- src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/LifecycleNonPrivate.java
- src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
- src/main/java/org/openrewrite/java/testing/junit5/ParameterizedRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/TempDirNonFinal.java
- src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
- src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java
- src/main/java/org/openrewrite/java/testing/mockito/CleanupMockitoImports.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.OperatorWrap?organizationId=T3BlblJld3JpdGU%3D#defaults=W3sidmFsdWUiOiJFT0wiLCJuYW1lIjoid3JhcE9wdGlvbiJ9XQ==
> refactor: Operator wrapping on end of line

- build.gradle.kts
- suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/741
> update to latest error prone to remove protobuf-java@3.19.2 vulnerability

- src/main/java/org/openrewrite/java/testing/cleanup/RemoveEmptyTests.java
- src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
- src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java
- src/main/java/org/openrewrite/java/testing/junit5/TestRuleToTestInfo.java
- src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
Use this link to re-run the recipe: https://app.moderne.io/builder/ji8mLIdUI?organizationId=T3BlblJld3JpdGU%3D
> refactor: add @Nullable to methods who may return null

- src/test/java/org/openrewrite/java/testing/mockito/Mockito1to5MigrationTest.java
> improve assertions in Mockito1to5MigrationTest

- src/main/java/org/openrewrite/java/testing/cleanup/AssertEqualsBooleanToAssertBoolean.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertFalseNegationToAssertTrue.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertNotEqualsBooleanToAssertBoolean.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueComparisonToAssertEquals.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertTrueNegationToAssertFalse.java
- src/main/java/org/openrewrite/java/testing/junit5/AddMissingNested.java
- src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.CompareEnumsWithEqualityOperator?organizationId=T3BlblJld3JpdGU%3D
> refactor: Enum values should be compared with "=="

- src/main/java/org/openrewrite/java/testing/hamcrest/RemoveNotMatcherVisitor.java
- src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestInstanceOfToJUnit5Test.java
- src/test/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToJUnit5Test.java
- src/test/java/org/openrewrite/java/testing/hamcrest/MigrateHamcrestToJUnitTest.java
- src/test/java/org/openrewrite/java/testing/hamcrest/RemoveNotMatcherTest.java
- https://github.com/openrewrite/rewrite/pull/4879
> Suppress mutable execution context warnings for now

- src/main/java/org/openrewrite/java/testing/junit5/GradleUseJunitJupiter.java
- src/test/java/org/openrewrite/java/testing/junit5/GradleUseJunitJupiterTest.java
Nothing, just refactoring of the GradleUseJunitJupiter. Also added a missing unit test.
Completing:
- https://github.com/openrewrite/rewrite-testing-frameworks/commit/bf03fa20a5aebe1f9b881aa7e3ec44143e085bdc
> Refactor GradleUseJunitJupiter

- src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
- src/test/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterizedTest.java
Added support for CsvSource migration for JUnitParamsRunnerToParameterizedTest Recipe
> Add support for CsvSource migration

- src/main/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMock.java
- src/test/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMockTest.java
When ReplaceInitMockToOpenMock recipe add `mocks.close()` to a method it doesn't add throws declaration if it was missing due to which compilation fails after migration.
Updated recipe to handle this case.
> Fix exception handling in ReplaceInitMockito recipe

- src/main/java/org/openrewrite/java/testing/junit5/ExpectedExceptionToAssertThrows.java
Seemed not needed from the tests, and we also saw this recipe consistently take a long time to run.
> Drop `contextSensitive` from `ExpectedExceptionToAssertThrows`

- src/main/java/org/openrewrite/java/testing/mockito/CloseUnclosedStaticMocks.java
- src/test/java/org/openrewrite/java/testing/mockito/CloseUnclosedStaticMocksTest.java
Handle Nested class, qualified mocked class names.
- Followup pr #739
> CloseUnclosedStaticMocks: Handle Nested class, qualifiedclass name.

- src/main/resources/META-INF/rewrite/testcontainers.yml
- src/test/java/org/openrewrite/java/testing/testcontainers/TestcontainersBestPracticesTest.java
testcontainers 1.19.x --> 1.21.x
> testcontainers 1.21.x

- build.gradle.kts
- src/main/java/org/openrewrite/java/testing/mockito/NoInitializationForInjectMock.java
- src/test/java/org/openrewrite/java/testing/mockito/NoInitializationForInjectMockTest.java
> Remove `@InjectMocks` from initialized fields

- src/main/java/org/openrewrite/java/testing/assertj/CollapseConsecutiveAssertThatStatements.java
- src/test/java/org/openrewrite/java/testing/assertj/CollapseConsecutiveAssertThatStatementsTest.java
> Collapse more consecutive assertions

- src/main/java/org/openrewrite/java/testing/assertj/AdoptAssertJDurationAssertions.java
- src/main/java/org/openrewrite/java/testing/cleanup/AssertionsArgumentOrder.java
- src/main/java/org/openrewrite/java/testing/dbrider/ExecutionListenerToDbRiderAnnotation.java
- src/main/java/org/openrewrite/java/testing/hamcrest/HamcrestMatcherToAssertJ.java
- src/main/java/org/openrewrite/java/testing/hamcrest/RemoveNotMatcherVisitor.java
- src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
- src/main/java/org/openrewrite/java/testing/jmockit/SetupStatementsRewriter.java
- src/main/java/org/openrewrite/java/testing/junit5/CategoryToTag.java
- src/main/java/org/openrewrite/java/testing/junit5/JUnitParamsRunnerToParameterized.java
- src/main/java/org/openrewrite/java/testing/junit5/MigrateJUnitTestCase.java
- src/main/java/org/openrewrite/java/testing/junit5/RemoveTryCatchFailBlocks.java
- src/main/java/org/openrewrite/java/testing/junit5/UseAssertSame.java
- src/main/java/org/openrewrite/java/testing/junit5/UseWiremockExtension.java
- src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java
- src/main/java/org/openrewrite/java/testing/mockito/ReplaceInitMockToOpenMock.java
- src/main/java/org/openrewrite/java/testing/testng/TestNgAssertEqualsToAssertThat.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UnwrapElseAfterReturn?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw
> refactor: Unwrap else block after return or throw statement

- src/main/resources/META-INF/rewrite/assertj.yml
- src/test/java/org/openrewrite/java/testing/assertj/AssertJBestPracticesTest.java
Based on https://github.com/PicnicSupermarket/error-prone-support/releases/tag/v0.24.0
> Include additional AssertJ migrations

- src/main/java/org/openrewrite/java/testing/mockito/VerifyZeroToNoMoreInteractions.java
- src/main/resources/META-INF/rewrite/junit5.yml
Identified via https://docs.openrewrite.org/reference/standalone-recipes
> Include recipes in larger composites where possible

- src/test/java/org/openrewrite/java/testing/truth/MigrateTruthToAssertJTest.java
add unit test for Google Truth migration
> truth migration adds assertj-core

- src/main/resources/META-INF/rewrite/examples.yml
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
> OpenRewrite recipe best practices

- src/main/java/org/openrewrite/java/testing/jmockit/JMockitBlockRewriter.java
- src/main/java/org/openrewrite/java/testing/mockito/MockitoWhenOnStaticToMockStatic.java
- src/main/resources/META-INF/rewrite/examples.yml
- src/test/java/org/openrewrite/java/testing/junit5/AddMissingTestBeforeAfterAnnotationsTest.java
- src/test/java/org/openrewrite/java/testing/junit5/CategoryToTagTest.java
- src/test/java/org/openrewrite/java/testing/junit5/UpgradeOkHttpMockWebServerTest.java
- src/test/java/org/openrewrite/java/testing/mockito/AnyStringToNullableTest.java
- src/test/java/org/openrewrite/java/testing/mockito/AnyToNullableTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw
> Update recipe documentation examples
